coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
        informational: true
    patch:
      default:
        target: 80%

ignore:
  - "lambda/**/tests/**"
  - "terraform-tests/**"
  - "**/__pycache__/**"
